### ISSUE TITLE
[css-nav-1] Improve the name of window.navigate

### ISSUE THREAD

**Issue by frivoal** [lgeweb/spatial-navigation#120]
Previously in #70, we discussed whether `window.navigate()` was a great name for this API or not. It seems like it could be confused with navigating to a new URL, so some better name would be good.

However, no suggestion so far seems to work:
* `focusNavigate()` or other names invoking focus are wrong, because it can also scroll things instead of focusing them
* `directionalNavigate()` or `spatialNavigate()` or similar are also problematic, because this method should be possible to extend to sequential navigation by passing it a `"prev"` or `"next"` argument, and that does not work with such names.

So, leaving this issue open to see if we can do better.

**Comment by hugoholgersson** [comment]
`stepFocusOrScroll`
